[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
# my libraries
importer = { path = "../importer/" }
shared = { path = "../shared/" }
db = { path = "../db/" }
charter = { path = "../charter/" }
# external libraries
anyhow = "1.0.104"
log = "0.4.33"
simple_logger = "5.2.0"
tokio = { version = "1.53.1", features = ["full"] }
